var baseURL = '/common/js/';
document.write('<script type="text/javascript" src="'+baseURL+'plugins/EasePack.js"></script>');
document.write('<script type="text/javascript" src="'+baseURL+'plugins/TweenMax.js"></script>');
document.write('<script type="text/javascript" src="'+baseURL+'pub/variables.js"></script>');
document.write('<script type="text/javascript" src="'+baseURL+'pub/device.js"></script>');
document.write('<script type="text/javascript" src="'+baseURL+'pub/utility.js"></script>');
document.write('<script type="text/javascript" src="'+baseURL+'pub/common.js"></script>');
document.write('<script type="text/javascript" src="'+baseURL+'pub/ui.js"></script>');
document.write('<script type="text/javascript" src="'+baseURL+'pub/content.js"></script>');
document.write('<script type="text/javascript" src="'+baseURL+'pub/main.js"></script>');
document.write('<script type="text/javascript" src="'+baseURL+'pub/init.js"></script>');
document.write('<!--[if lt IE 9]>');
document.write('<script type="text/javascript" src="'+baseURL+'libs/html5shiv-printshiv.js"></script>');
document.write('<![endif]-->');
